add fallback non-pkgconfig search for libXi for older systems
(Old svn revision: 29925)

diff --git a/configure.ac.in b/configure.ac.in
--- a/configure.ac.in
+++ b/configure.ac.in
@@ -82,9 +82,36 @@ XDT_CHECK_PACKAGE([LIBXFCE4KBD_PRIVATE], [libxfce4kbd-private-1.0], [4.6.0])
 XDT_CHECK_PACKAGE([GLADE], [libglade-2.0], [2.0.0])
 XDT_CHECK_PACKAGE([XFCONF], [libxfconf-0], [4.6.0])
 XDT_CHECK_PACKAGE([DBUS_GLIB], [dbus-glib-1], [0.34])
-XDT_CHECK_PACKAGE([XI], [xi], [1.0.0])
-XDT_CHECK_PACKAGE([LIBX11], [x11], [1.0.0])
 XDT_CHECK_PACKAGE([LIBWNCK], [libwnck-1.0], [2.12.0])
+
+XDT_CHECK_PACKAGE([XI], [xi], [1.0.0], [],
+[
+  for dir in /usr/X11R6 /usr/X11 /opt/X11R6 /opt/X11; do
+    test -z "$XI_CFLAGS" || break
+    saved_CFLAGS="$CFLAGS"
+    saved_LIBS="$LIBS"
+    CFLAGS="$CFLAGS -I$dir/include"
+    LIBS="$LIBS -L$dir/lib"
+    AC_CHECK_LIB([Xi], [XListInputDevices],
+    [
+      XI_CFLAGS="-I$dir/include"
+      XI_LIBS="-L$dir/lib -lXi"
+      AC_SUBST(XI_CFLAGS)
+      AC_SUBST(XI_LIBS)
+    ])
+    CFLAGS="$saved_CFLAGS"
+    LIBS="$saved_LIBS"
+  done
+  if test -z "$XI_CFLAGS"; then
+    echo "*** The required package Xi was not found on your system."
+    echo "*** Please install Xi or adjust the PKG_CONFIG_PATH environment"
+    echo "*** variable if you installed the package in a nonstandard"
+    echo "*** prefix so that pkg-config is able to find it."
+    exit 1
+  fi
+])
+
+XDT_CHECK_PACKAGE([LIBX11], [x11], [1.0.0], [], [XDT_CHECK_LIBX11_REQUIRE])
 
 dnl ***********************************
 dnl *** Optional support for Xrandr ***
